"""collector schema

Revision ID: 0001
Revises:
Create Date: 2026-09-26 22:28:54.972744

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "season",
        sa.Column("label", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("label"),
    )
    op.create_table(
        "gameweek",
        sa.Column("season", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("fpl_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("deadline_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished", sa.Boolean(), nullable=False),
        sa.Column("data_checked", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["season"],
            ["season.label"],
        ),
        sa.PrimaryKeyConstraint("season", "fpl_id"),
    )
    op.create_table(
        "league",
        sa.Column("season", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("fpl_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["season"],
            ["season.label"],
        ),
        sa.PrimaryKeyConstraint("season", "fpl_id"),
    )
    op.create_table(
        "manager",
        sa.Column("season", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("entry_id", sa.Integer(), nullable=False),
        sa.Column("team_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("manager_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["season"],
            ["season.label"],
        ),
        sa.PrimaryKeyConstraint("season", "entry_id"),
    )
    op.create_table(
        "raw_payload",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("season", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("endpoint", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("gameweek_fpl_id", sa.Integer(), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["season"],
            ["season.label"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "team",
        sa.Column("season", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("fpl_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("short_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["season"],
            ["season.label"],
        ),
        sa.PrimaryKeyConstraint("season", "fpl_id"),
    )
    op.create_table(
        "fixture",
        sa.Column("season", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("fpl_id", sa.Integer(), nullable=False),
        sa.Column("gameweek_fpl_id", sa.Integer(), nullable=True),
        sa.Column("kickoff_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("team_h_fpl_id", sa.Integer(), nullable=False),
        sa.Column("team_a_fpl_id", sa.Integer(), nullable=False),
        sa.Column("team_h_score", sa.Integer(), nullable=True),
        sa.Column("team_a_score", sa.Integer(), nullable=True),
        sa.Column("finished", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["season", "gameweek_fpl_id"],
            ["gameweek.season", "gameweek.fpl_id"],
        ),
        sa.ForeignKeyConstraint(
            ["season", "team_a_fpl_id"],
            ["team.season", "team.fpl_id"],
        ),
        sa.ForeignKeyConstraint(
            ["season", "team_h_fpl_id"],
            ["team.season", "team.fpl_id"],
        ),
        sa.ForeignKeyConstraint(
            ["season"],
            ["season.label"],
        ),
        sa.PrimaryKeyConstraint("season", "fpl_id"),
    )
    op.create_table(
        "league_membership",
        sa.Column("season", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("league_fpl_id", sa.Integer(), nullable=False),
        sa.Column("entry_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["season", "entry_id"],
            ["manager.season", "manager.entry_id"],
        ),
        sa.ForeignKeyConstraint(
            ["season", "league_fpl_id"],
            ["league.season", "league.fpl_id"],
        ),
        sa.ForeignKeyConstraint(
            ["season"],
            ["season.label"],
        ),
        sa.PrimaryKeyConstraint("season", "league_fpl_id", "entry_id"),
    )
    op.create_table(
        "league_standing",
        sa.Column("season", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("league_fpl_id", sa.Integer(), nullable=False),
        sa.Column("gameweek_fpl_id", sa.Integer(), nullable=False),
        sa.Column("entry_id", sa.Integer(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("event_total", sa.Integer(), nullable=False),
        sa.Column("total", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["season", "entry_id"],
            ["manager.season", "manager.entry_id"],
        ),
        sa.ForeignKeyConstraint(
            ["season", "gameweek_fpl_id"],
            ["gameweek.season", "gameweek.fpl_id"],
        ),
        sa.ForeignKeyConstraint(
            ["season", "league_fpl_id"],
            ["league.season", "league.fpl_id"],
        ),
        sa.ForeignKeyConstraint(
            ["season"],
            ["season.label"],
        ),
        sa.PrimaryKeyConstraint("season", "league_fpl_id", "gameweek_fpl_id", "entry_id"),
    )
    op.create_table(
        "manager_chip",
        sa.Column("season", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("entry_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("gameweek_fpl_id", sa.Integer(), nullable=False),
        sa.Column("played_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["season", "entry_id"],
            ["manager.season", "manager.entry_id"],
        ),
        sa.ForeignKeyConstraint(
            ["season", "gameweek_fpl_id"],
            ["gameweek.season", "gameweek.fpl_id"],
        ),
        sa.ForeignKeyConstraint(
            ["season"],
            ["season.label"],
        ),
        sa.PrimaryKeyConstraint("season", "entry_id", "name", "gameweek_fpl_id"),
    )
    op.create_table(
        "manager_gameweek",
        sa.Column("season", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("entry_id", sa.Integer(), nullable=False),
        sa.Column("gameweek_fpl_id", sa.Integer(), nullable=False),
        sa.Column("has_team", sa.Boolean(), nullable=False),
        sa.Column("active_chip", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("points", sa.Integer(), nullable=True),
        sa.Column("total_points", sa.Integer(), nullable=True),
        sa.Column("event_transfers", sa.Integer(), nullable=True),
        sa.Column("event_transfers_cost", sa.Integer(), nullable=True),
        sa.Column("points_on_bench", sa.Integer(), nullable=True),
        sa.Column("bank", sa.Integer(), nullable=True),
        sa.Column("value", sa.Integer(), nullable=True),
        sa.Column("overall_rank", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["season", "entry_id"],
            ["manager.season", "manager.entry_id"],
        ),
        sa.ForeignKeyConstraint(
            ["season", "gameweek_fpl_id"],
            ["gameweek.season", "gameweek.fpl_id"],
        ),
        sa.ForeignKeyConstraint(
            ["season"],
            ["season.label"],
        ),
        sa.PrimaryKeyConstraint("season", "entry_id", "gameweek_fpl_id"),
    )
    op.create_table(
        "player",
        sa.Column("season", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("fpl_id", sa.Integer(), nullable=False),
        sa.Column("web_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("first_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("second_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("team_fpl_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["season", "team_fpl_id"],
            ["team.season", "team.fpl_id"],
        ),
        sa.ForeignKeyConstraint(
            ["season"],
            ["season.label"],
        ),
        sa.PrimaryKeyConstraint("season", "fpl_id"),
    )
    op.create_table(
        "deadline_snapshot_player",
        sa.Column("season", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("gameweek_fpl_id", sa.Integer(), nullable=False),
        sa.Column("player_fpl_id", sa.Integer(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("news", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("chance_of_playing_this_round", sa.Integer(), nullable=True),
        sa.Column("chance_of_playing_next_round", sa.Integer(), nullable=True),
        sa.Column("selected_by_percent", sa.Numeric(precision=5, scale=1), nullable=False),
        sa.Column("now_cost", sa.Integer(), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["season", "gameweek_fpl_id"],
            ["gameweek.season", "gameweek.fpl_id"],
        ),
        sa.ForeignKeyConstraint(
            ["season", "player_fpl_id"],
            ["player.season", "player.fpl_id"],
        ),
        sa.ForeignKeyConstraint(
            ["season"],
            ["season.label"],
        ),
        sa.PrimaryKeyConstraint("season", "gameweek_fpl_id", "player_fpl_id"),
    )
    op.create_table(
        "manager_auto_sub",
        sa.Column("season", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("entry_id", sa.Integer(), nullable=False),
        sa.Column("gameweek_fpl_id", sa.Integer(), nullable=False),
        sa.Column("player_out_fpl_id", sa.Integer(), nullable=False),
        sa.Column("player_in_fpl_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["season", "entry_id", "gameweek_fpl_id"],
            [
                "manager_gameweek.season",
                "manager_gameweek.entry_id",
                "manager_gameweek.gameweek_fpl_id",
            ],
        ),
        sa.ForeignKeyConstraint(
            ["season", "player_in_fpl_id"],
            ["player.season", "player.fpl_id"],
        ),
        sa.ForeignKeyConstraint(
            ["season", "player_out_fpl_id"],
            ["player.season", "player.fpl_id"],
        ),
        sa.ForeignKeyConstraint(
            ["season"],
            ["season.label"],
        ),
        sa.PrimaryKeyConstraint("season", "entry_id", "gameweek_fpl_id", "player_out_fpl_id"),
    )
    op.create_table(
        "manager_pick",
        sa.Column("season", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("entry_id", sa.Integer(), nullable=False),
        sa.Column("gameweek_fpl_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("player_fpl_id", sa.Integer(), nullable=False),
        sa.Column("multiplier", sa.Integer(), nullable=False),
        sa.Column("is_captain", sa.Boolean(), nullable=False),
        sa.Column("is_vice_captain", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["season", "entry_id", "gameweek_fpl_id"],
            [
                "manager_gameweek.season",
                "manager_gameweek.entry_id",
                "manager_gameweek.gameweek_fpl_id",
            ],
        ),
        sa.ForeignKeyConstraint(
            ["season", "player_fpl_id"],
            ["player.season", "player.fpl_id"],
        ),
        sa.ForeignKeyConstraint(
            ["season"],
            ["season.label"],
        ),
        sa.PrimaryKeyConstraint("season", "entry_id", "gameweek_fpl_id", "position"),
    )
    op.create_table(
        "manager_transfer",
        sa.Column("season", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("entry_id", sa.Integer(), nullable=False),
        sa.Column("made_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("player_in_fpl_id", sa.Integer(), nullable=False),
        sa.Column("gameweek_fpl_id", sa.Integer(), nullable=False),
        sa.Column("player_out_fpl_id", sa.Integer(), nullable=False),
        sa.Column("player_in_cost", sa.Integer(), nullable=False),
        sa.Column("player_out_cost", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["season", "entry_id"],
            ["manager.season", "manager.entry_id"],
        ),
        sa.ForeignKeyConstraint(
            ["season", "gameweek_fpl_id"],
            ["gameweek.season", "gameweek.fpl_id"],
        ),
        sa.ForeignKeyConstraint(
            ["season", "player_in_fpl_id"],
            ["player.season", "player.fpl_id"],
        ),
        sa.ForeignKeyConstraint(
            ["season", "player_out_fpl_id"],
            ["player.season", "player.fpl_id"],
        ),
        sa.ForeignKeyConstraint(
            ["season"],
            ["season.label"],
        ),
        sa.PrimaryKeyConstraint("season", "entry_id", "made_at", "player_in_fpl_id"),
    )
    op.create_table(
        "player_flag_change",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("season", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("player_fpl_id", sa.Integer(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("news", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("news_added", sa.DateTime(timezone=True), nullable=True),
        sa.Column("chance_of_playing_this_round", sa.Integer(), nullable=True),
        sa.Column("chance_of_playing_next_round", sa.Integer(), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["season", "player_fpl_id"],
            ["player.season", "player.fpl_id"],
        ),
        sa.ForeignKeyConstraint(
            ["season"],
            ["season.label"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_player_flag_change_season_player_observed",
        "player_flag_change",
        ["season", "player_fpl_id", "observed_at"],
        unique=False,
    )
    op.create_table(
        "player_gameweek_result",
        sa.Column("season", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("player_fpl_id", sa.Integer(), nullable=False),
        sa.Column("gameweek_fpl_id", sa.Integer(), nullable=False),
        sa.Column("starts", sa.Integer(), nullable=False),
        sa.Column("minutes", sa.Integer(), nullable=False),
        sa.Column("total_points", sa.Integer(), nullable=False),
        sa.Column("explain", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["season", "gameweek_fpl_id"],
            ["gameweek.season", "gameweek.fpl_id"],
        ),
        sa.ForeignKeyConstraint(
            ["season", "player_fpl_id"],
            ["player.season", "player.fpl_id"],
        ),
        sa.ForeignKeyConstraint(
            ["season"],
            ["season.label"],
        ),
        sa.PrimaryKeyConstraint("season", "player_fpl_id", "gameweek_fpl_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("player_gameweek_result")
    op.drop_index("ix_player_flag_change_season_player_observed", table_name="player_flag_change")
    op.drop_table("player_flag_change")
    op.drop_table("manager_transfer")
    op.drop_table("manager_pick")
    op.drop_table("manager_auto_sub")
    op.drop_table("deadline_snapshot_player")
    op.drop_table("player")
    op.drop_table("manager_gameweek")
    op.drop_table("manager_chip")
    op.drop_table("league_standing")
    op.drop_table("league_membership")
    op.drop_table("fixture")
    op.drop_table("team")
    op.drop_table("raw_payload")
    op.drop_table("manager")
    op.drop_table("league")
    op.drop_table("gameweek")
    op.drop_table("season")
    # ### end Alembic commands ###
